name: CI

on:
  push:
    branches: [main]
    paths:
      - "lua/**"
      - "plugin/**"
      - "tests/**"
      - ".github/workflows/ci.yml"
      - "Makefile"
  pull_request:
    paths:
      - "lua/**"
      - "plugin/**"
      - "tests/**"
      - ".github/workflows/ci.yml"
      - "Makefile"

jobs:
  test:
    name: Test (nvim ${{ matrix.neovim }}, ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        neovim: ["v0.9.5", "v0.10.4", "nightly"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: rhysd/action-setup-vim@19e3dd31a84dbc2c5445d65e9b363f616cab96c1 # v1.6.0
        with:
          neovim: true
          version: ${{ matrix.neovim }}

      - name: Run tests
        run: make test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: AlejandroSuero/selene-linter-action@f50a6d44c48edcc56429269592cbad4e940a40c0 # v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --display-style=quiet lua/ plugin/ tests/

  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: stevearc/nvim-typecheck-action@a2c7bff1c2f1d8489106271c8f89183628d41655 # v2
        with:
          path: lua
          level: Warning

  format:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: JohnnyMorganz/stylua-action@479972f01e665acfcba96ada452c36608bdbbb5e # v4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua/ plugin/ tests/

  ci:
    if: always()
    needs: [test, lint, typecheck, format]
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1
        with:
          jobs: ${{ toJSON(needs) }}
