name: Generate Docs

on:
  push:
    branches: [main]
    paths:
      - "README.md"

permissions:
  contents: write

jobs:
  docs:
    name: Generate vimdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: kdheepak/panvimdoc@662fb20304d20c539fb48a0bda628f5165507de7 # v4.0.1
        with:
          vimdoc: nit

      - uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          commit_message: "chore(docs): auto-generate vimdoc"
          file_pattern: "doc/*.txt"
